name: Deploy to nginx web-server in Vagrant VM 

on: 
  push:
    branches: [ "main" ]
    paths-ignore: 
      - '.github/workflows/*'  # Ignore workflow file changes


jobs:
  deploy:
    runs-on: self-hosted

    # Prevent pipeline from triggering if the only change is to the deploy workflow file itself
    if: |
      !contains(github.event.head_commit.modified, '.github/workflows/deploy.yml') &&
      github.event_name == 'push'
  
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Deploy files to nginx 
      run: |
        # Remove old files
        sudo rm -rf /var/www/site1.local/*
        
        # Copy only site files
        sudo cp -r sample-website/* /var/www/site1.local/

        # Set proper permissions
        sudo chown -R nginx:nginx /var/www/site1.local
        sudo chmod -R 755 /var/www/site1.local
        
        # Optional: Restart Nginx if needed
        # sudo systemctl restart nginx
